---
- name: install the ceph stable repository key
  rpm_key:
    key: "{{ ceph_stable_key }}"
    state: present
  when: ceph_stable

- name: install the ceph development repository key
  rpm_key:
    key: "{{ ceph_dev_key }}"
    state: present
  when: ceph_dev

- name: add ceph stable repository
  yum:
    name: http://download.ceph.com/rpm-{{ ceph_stable_release }}/{{ ceph_stable_redhat_distro }}/noarch/ceph-release-1-0.{{ ceph_stable_redhat_distro|replace('rhel', 'el') }}.noarch.rpm
  changed_when: false
  when:
    - ceph_stable
    - ansible_pkg_mgr == "yum"

- name: add ceph stable repository
  dnf:
    name: http://download.ceph.com/rpm-{{ ceph_stable_release }}/{{ ceph_stable_redhat_distro }}/noarch/ceph-release-1-0.{{ ceph_stable_redhat_distro|replace('rhel', 'el') }}.noarch.rpm
  changed_when: false
  when:
    - ceph_stable
    - ansible_pkg_mgr == "dnf"

- name: add ceph development repository
  yum:
    name: http://gitbuilder.ceph.com/ceph-rpm-{{ ceph_dev_redhat_distro }}-x86_64-basic/ref/{{ ceph_dev_branch }}/noarch/ceph-release-1-0.{{ ceph_stable_redhat_distro }}.noarch.rpm
  changed_when: false
  when:
    - ceph_dev
    - ansible_pkg_mgr == "yum"

- name: add ceph development repository
  dnf:
    name: http://gitbuilder.ceph.com/ceph-rpm-{{ ceph_dev_redhat_distro }}-x86_64-basic/ref/{{ ceph_dev_branch }}/noarch/ceph-release-1-0.{{ ceph_stable_redhat_distro }}.noarch.rpm
  changed_when: false
  when:
    - ceph_dev
    - ansible_pkg_mgr == "dnf"

- name: add custom repo
  get_url:
    url: "{{ ceph_custom_repo }}"
    dest: /etc/yum.repos.d
    owner: root
    group: root
  when: ceph_custom

# Remove yum caches so yum doesn't get confused if we are reinstalling a different ceph version
- name: purge yum cache
  command: yum clean all
  when:
    ansible_pkg_mgr == 'yum'
