---
- include: ../checks/check_ntp_atomic.yml
  when: ansible_os_family == 'RedHat'

- name: start the ntp service
  service:
    name: chronyd
    enabled: yes
    state: started
  when:
    - ntp_pkg_query.rc == 0
